export const GET_ROOT_SECTIONS_PENDING = 'GET_ROOT_SECTIONS_PENDING';
export const GET_ROOT_SECTIONS_SUCCESS = 'GET_ROOT_SECTIONS_SUCCESS';

export const GET_SUB_SECTIONS_PENDING = 'GET_SUB_SECTIONS_PENDING';
export const GET_SUB_SECTIONS_SUCCESS = 'GET_SUB_SECTIONS_SUCCESS';

export const REMOVE_SUB_SECTIONS_SUCCESS = 'REMOVE_SUB_SECTIONS_SUCCESS';

export const ADD_SELECTED_SECTIONS = 'ADD_SELECTED_SECTIONS';
export const REMOVE_SELECTED_SECTIONS = 'REMOVE_SELECTED_SECTIONS';
